# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/namegen.ui'
#
# Created: Sun Aug 16 12:04:50 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName(_fromUtf8("Window"))
        Window.resize(704, 515)
        self.tabWidget = QtGui.QTabWidget(Window)
        self.tabWidget.setGeometry(QtCore.QRect(10, 80, 681, 421))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabSelect = QtGui.QWidget()
        self.tabSelect.setObjectName(_fromUtf8("tabSelect"))
        self.treeWidget = QtGui.QTreeWidget(self.tabSelect)
        self.treeWidget.setGeometry(QtCore.QRect(10, 100, 651, 220))
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.treeWidget.setIndentation(10)
        self.treeWidget.setRootIsDecorated(False)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.header().setVisible(True)
        self.treeWidget.header().setDefaultSectionSize(60)
        self.treeWidget.header().setHighlightSections(True)
        self.treeWidget.header().setMinimumSectionSize(2)
        self.treeWidget.header().setSortIndicatorShown(True)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.tabSelect)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 10, 641, 33))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.lineSpecies = QtGui.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineSpecies.setObjectName(_fromUtf8("lineSpecies"))
        self.horizontalLayout_3.addWidget(self.lineSpecies)
        self.butAddToTree = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.butAddToTree.setObjectName(_fromUtf8("butAddToTree"))
        self.horizontalLayout_3.addWidget(self.butAddToTree)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.tabSelect)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(490, 340, 171, 41))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.butGenerateSp = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.butGenerateSp.setObjectName(_fromUtf8("butGenerateSp"))
        self.horizontalLayout_4.addWidget(self.butGenerateSp)
        self.butClose1 = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.butClose1.setObjectName(_fromUtf8("butClose1"))
        self.horizontalLayout_4.addWidget(self.butClose1)
        self.horizontalLayoutWidget = QtGui.QWidget(self.tabSelect)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 330, 291, 32))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.butDeleteSelection = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.butDeleteSelection.setObjectName(_fromUtf8("butDeleteSelection"))
        self.horizontalLayout.addWidget(self.butDeleteSelection)
        self.butDeleteAll = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.butDeleteAll.setObjectName(_fromUtf8("butDeleteAll"))
        self.horizontalLayout.addWidget(self.butDeleteAll)
        self.horizontalLayoutWidget_6 = QtGui.QWidget(self.tabSelect)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(20, 50, 641, 33))
        self.horizontalLayoutWidget_6.setObjectName(_fromUtf8("horizontalLayoutWidget_6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_6 = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_6.addWidget(self.label_6)
        self.lineTempFile = QtGui.QLineEdit(self.horizontalLayoutWidget_6)
        self.lineTempFile.setObjectName(_fromUtf8("lineTempFile"))
        self.horizontalLayout_6.addWidget(self.lineTempFile)
        self.butSelectTempFile = QtGui.QPushButton(self.horizontalLayoutWidget_6)
        self.butSelectTempFile.setObjectName(_fromUtf8("butSelectTempFile"))
        self.horizontalLayout_6.addWidget(self.butSelectTempFile)
        self.tabWidget.addTab(self.tabSelect, _fromUtf8(""))
        self.tabBatch = QtGui.QWidget()
        self.tabBatch.setObjectName(_fromUtf8("tabBatch"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.tabBatch)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(60, 30, 571, 80))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lineSlist = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineSlist.setObjectName(_fromUtf8("lineSlist"))
        self.horizontalLayout_2.addWidget(self.lineSlist)
        self.butSlist = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.butSlist.setObjectName(_fromUtf8("butSlist"))
        self.horizontalLayout_2.addWidget(self.butSlist)
        self.horizontalLayoutWidget_5 = QtGui.QWidget(self.tabBatch)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(490, 330, 171, 41))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.butGenerate = QtGui.QPushButton(self.horizontalLayoutWidget_5)
        self.butGenerate.setObjectName(_fromUtf8("butGenerate"))
        self.horizontalLayout_5.addWidget(self.butGenerate)
        self.butClose = QtGui.QPushButton(self.horizontalLayoutWidget_5)
        self.butClose.setObjectName(_fromUtf8("butClose"))
        self.horizontalLayout_5.addWidget(self.butClose)
        self.tabWidget.addTab(self.tabBatch, _fromUtf8(""))
        self.gridLayoutWidget_2 = QtGui.QWidget(Window)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 411, 61))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lineBlist = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineBlist.setText(_fromUtf8(""))
        self.lineBlist.setObjectName(_fromUtf8("lineBlist"))
        self.gridLayout_2.addWidget(self.lineBlist, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.butBlist = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.butBlist.setObjectName(_fromUtf8("butBlist"))
        self.gridLayout_2.addWidget(self.butBlist, 0, 2, 1, 1)
        self.lineOutputFilename = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.lineOutputFilename.setText(_fromUtf8(""))
        self.lineOutputFilename.setObjectName(_fromUtf8("lineOutputFilename"))
        self.gridLayout_2.addWidget(self.lineOutputFilename, 1, 1, 1, 1)
        self.butSelectOutput = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.butSelectOutput.setObjectName(_fromUtf8("butSelectOutput"))
        self.gridLayout_2.addWidget(self.butSelectOutput, 1, 2, 1, 1)

        self.retranslateUi(Window)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.butClose1, QtCore.SIGNAL(_fromUtf8("clicked()")), Window.close)
        QtCore.QObject.connect(self.butClose, QtCore.SIGNAL(_fromUtf8("clicked()")), Window.close)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        Window.setWindowTitle(_translate("Window", "物種名錄產生器 namelist generator", None))
        self.treeWidget.setSortingEnabled(True)
        self.treeWidget.headerItem().setText(0, _translate("Window", "Family", None))
        self.treeWidget.headerItem().setText(1, _translate("Window", "Name", None))
        self.treeWidget.headerItem().setText(2, _translate("Window", "Localname", None))
        self.label_5.setText(_translate("Window", "中文俗名", None))
        self.butAddToTree.setText(_translate("Window", "加入清單", None))
        self.butGenerateSp.setText(_translate("Window", "產生名錄", None))
        self.butClose1.setText(_translate("Window", "關閉", None))
        self.butDeleteSelection.setText(_translate("Window", "刪除所選物種", None))
        self.butDeleteAll.setText(_translate("Window", "刪除所有物種", None))
        self.label_6.setText(_translate("Window", "物種中名暫存檔", None))
        self.butSelectTempFile.setText(_translate("Window", "選擇檔案", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSelect), _translate("Window", "選擇物種", None))
        self.label_4.setText(_translate("Window", "產生名錄之物種csv檔案", None))
        self.butSlist.setText(_translate("Window", "選擇檔案", None))
        self.butGenerate.setText(_translate("Window", "產生名錄", None))
        self.butClose.setText(_translate("Window", "關閉", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBatch), _translate("Window", "批次匯入", None))
        self.label_2.setText(_translate("Window", "輸出名錄檔案", None))
        self.label.setText(_translate("Window", "物種清單資料表", None))
        self.butBlist.setText(_translate("Window", "選擇檔案", None))
        self.butSelectOutput.setText(_translate("Window", "選擇檔案", None))

