# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/namegen.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(704, 515)
        self.tabWidget = QtWidgets.QTabWidget(Window)
        self.tabWidget.setGeometry(QtCore.QRect(10, 100, 681, 401))
        self.tabWidget.setObjectName("tabWidget")
        self.tabSelect = QtWidgets.QWidget()
        self.tabSelect.setObjectName("tabSelect")
        self.treeWidget = QtWidgets.QTreeWidget(self.tabSelect)
        self.treeWidget.setGeometry(QtCore.QRect(10, 100, 651, 220))
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.treeWidget.setIndentation(10)
        self.treeWidget.setRootIsDecorated(False)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.header().setVisible(True)
        self.treeWidget.header().setDefaultSectionSize(60)
        self.treeWidget.header().setHighlightSections(True)
        self.treeWidget.header().setMinimumSectionSize(2)
        self.treeWidget.header().setSortIndicatorShown(True)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.tabSelect)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(490, 340, 171, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.butGenerateSp = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.butGenerateSp.setObjectName("butGenerateSp")
        self.horizontalLayout_4.addWidget(self.butGenerateSp)
        self.butClose1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.butClose1.setObjectName("butClose1")
        self.horizontalLayout_4.addWidget(self.butClose1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tabSelect)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 330, 291, 32))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.butDeleteSelection = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.butDeleteSelection.setObjectName("butDeleteSelection")
        self.horizontalLayout.addWidget(self.butDeleteSelection)
        self.butDeleteAll = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.butDeleteAll.setObjectName("butDeleteAll")
        self.horizontalLayout.addWidget(self.butDeleteAll)
        self.gridLayoutWidget = QtWidgets.QWidget(self.tabSelect)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 641, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.butAddToTree = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.butAddToTree.setObjectName("butAddToTree")
        self.gridLayout.addWidget(self.butAddToTree, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.lineSpecies = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineSpecies.setObjectName("lineSpecies")
        self.gridLayout.addWidget(self.lineSpecies, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.lineTempFile = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineTempFile.setObjectName("lineTempFile")
        self.gridLayout.addWidget(self.lineTempFile, 1, 1, 1, 1)
        self.butSelectTempFile = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.butSelectTempFile.setObjectName("butSelectTempFile")
        self.gridLayout.addWidget(self.butSelectTempFile, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tabSelect, "")
        self.tabBatch = QtWidgets.QWidget()
        self.tabBatch.setObjectName("tabBatch")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tabBatch)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(60, 30, 571, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lineSlist = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineSlist.setObjectName("lineSlist")
        self.horizontalLayout_2.addWidget(self.lineSlist)
        self.butSlist = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.butSlist.setObjectName("butSlist")
        self.horizontalLayout_2.addWidget(self.butSlist)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.tabBatch)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(490, 330, 171, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.butGenerate = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.butGenerate.setObjectName("butGenerate")
        self.horizontalLayout_5.addWidget(self.butGenerate)
        self.butClose = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.butClose.setObjectName("butClose")
        self.horizontalLayout_5.addWidget(self.butClose)
        self.tabWidget.addTab(self.tabBatch, "")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Window)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 411, 81))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineBlist = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineBlist.setText("")
        self.lineBlist.setObjectName("lineBlist")
        self.gridLayout_2.addWidget(self.lineBlist, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.butBlist = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.butBlist.setObjectName("butBlist")
        self.gridLayout_2.addWidget(self.butBlist, 0, 2, 1, 1)
        self.lineOutputFilename = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineOutputFilename.setText("")
        self.lineOutputFilename.setObjectName("lineOutputFilename")
        self.gridLayout_2.addWidget(self.lineOutputFilename, 1, 1, 1, 1)
        self.butSelectOutput = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.butSelectOutput.setObjectName("butSelectOutput")
        self.gridLayout_2.addWidget(self.butSelectOutput, 1, 2, 1, 1)
        self.label.raise_()
        self.label_2.raise_()
        self.butBlist.raise_()
        self.lineOutputFilename.raise_()
        self.lineBlist.raise_()
        self.butSelectOutput.raise_()

        self.retranslateUi(Window)
        self.tabWidget.setCurrentIndex(0)
        self.butClose1.clicked.connect(Window.close)
        self.butClose.clicked.connect(Window.close)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "物種名錄產生器 namelist generator"))
        self.treeWidget.setSortingEnabled(True)
        self.treeWidget.headerItem().setText(0, _translate("Window", "科名"))
        self.treeWidget.headerItem().setText(1, _translate("Window", "學名"))
        self.treeWidget.headerItem().setText(2, _translate("Window", "中文名"))
        self.butGenerateSp.setText(_translate("Window", "產生名錄"))
        self.butClose1.setText(_translate("Window", "關閉"))
        self.butDeleteSelection.setText(_translate("Window", "刪除所選物種"))
        self.butDeleteAll.setText(_translate("Window", "刪除所有物種"))
        self.butAddToTree.setText(_translate("Window", "加入清單"))
        self.label_5.setText(_translate("Window", "中文名"))
        self.label_6.setText(_translate("Window", "物種中名暫存檔"))
        self.butSelectTempFile.setText(_translate("Window", "選擇檔案"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSelect), _translate("Window", "選擇物種"))
        self.label_4.setText(_translate("Window", "產生名錄之物種csv檔案"))
        self.butSlist.setText(_translate("Window", "選擇檔案"))
        self.butGenerate.setText(_translate("Window", "產生名錄"))
        self.butClose.setText(_translate("Window", "關閉"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBatch), _translate("Window", "批次匯入"))
        self.label_2.setText(_translate("Window", "輸出名錄檔案"))
        self.label.setText(_translate("Window", "物種清單資料表"))
        self.butBlist.setToolTip(_translate("Window", "<html><head/><body><p>選擇物種清單的資料表，這個資料表為 csv 檔案，以 UTF-8 編碼。</p></body></html>"))
        self.butBlist.setText(_translate("Window", "選擇檔案"))
        self.butSelectOutput.setText(_translate("Window", "選擇檔案"))

