# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_compare.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CompareDialog(object):
    def setupUi(self, CompareDialog):
        CompareDialog.setObjectName("CompareDialog")
        CompareDialog.resize(567, 232)
        self.gridLayout = QtWidgets.QGridLayout(CompareDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(CompareDialog)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 543, 208))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 3)
        self.labelChecklistA = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelChecklistA.setObjectName("labelChecklistA")
        self.gridLayout_2.addWidget(self.labelChecklistA, 1, 0, 1, 1)
        self.butCheckASelect = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.butCheckASelect.setObjectName("butCheckASelect")
        self.gridLayout_2.addWidget(self.butCheckASelect, 1, 5, 1, 1)
        self.labelChecklistB = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelChecklistB.setObjectName("labelChecklistB")
        self.gridLayout_2.addWidget(self.labelChecklistB, 2, 0, 1, 1)
        self.butCheckBSelect = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.butCheckBSelect.setObjectName("butCheckBSelect")
        self.gridLayout_2.addWidget(self.butCheckBSelect, 2, 5, 1, 1)
        self.lineSep = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.lineSep.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineSep.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineSep.setObjectName("lineSep")
        self.gridLayout_2.addWidget(self.lineSep, 3, 0, 1, 6)
        self.labelComparingMode = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelComparingMode.setObjectName("labelComparingMode")
        self.gridLayout_2.addWidget(self.labelComparingMode, 4, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(148, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 4, 4, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(313, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 5, 0, 1, 3)
        self.butClose = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.butClose.setObjectName("butClose")
        self.gridLayout_2.addWidget(self.butClose, 5, 3, 1, 2)
        self.butCompare = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.butCompare.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.butCompare.setDefault(True)
        self.butCompare.setObjectName("butCompare")
        self.gridLayout_2.addWidget(self.butCompare, 5, 5, 1, 1)
        self.comboABDifference = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboABDifference.sizePolicy().hasHeightForWidth())
        self.comboABDifference.setSizePolicy(sizePolicy)
        self.comboABDifference.setObjectName("comboABDifference")
        self.comboABDifference.addItem("")
        self.comboABDifference.addItem("")
        self.comboABDifference.addItem("")
        self.comboABDifference.addItem("")
        self.gridLayout_2.addWidget(self.comboABDifference, 4, 2, 1, 1)
        self.lineChecklistA = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineChecklistA.sizePolicy().hasHeightForWidth())
        self.lineChecklistA.setSizePolicy(sizePolicy)
        self.lineChecklistA.setObjectName("lineChecklistA")
        self.gridLayout_2.addWidget(self.lineChecklistA, 1, 1, 1, 3)
        self.lineChecklistB = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineChecklistB.sizePolicy().hasHeightForWidth())
        self.lineChecklistB.setSizePolicy(sizePolicy)
        self.lineChecklistB.setObjectName("lineChecklistB")
        self.gridLayout_2.addWidget(self.lineChecklistB, 2, 1, 1, 3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(CompareDialog)
        QtCore.QMetaObject.connectSlotsByName(CompareDialog)

    def retranslateUi(self, CompareDialog):
        _translate = QtCore.QCoreApplication.translate
        CompareDialog.setWindowTitle(_translate("CompareDialog", "Comparing two checklists"))
        self.label.setText(_translate("CompareDialog", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Comparing two checklists</span></p></body></html>"))
        self.labelChecklistA.setText(_translate("CompareDialog", "Checklist A"))
        self.butCheckASelect.setText(_translate("CompareDialog", "Select file ..."))
        self.labelChecklistB.setText(_translate("CompareDialog", "Checklist B"))
        self.butCheckBSelect.setText(_translate("CompareDialog", "Select file ..."))
        self.labelComparingMode.setText(_translate("CompareDialog", "Comparing mode"))
        self.butClose.setToolTip(_translate("CompareDialog", "<html><head/><body><p>Select export checklist file. Supported file formats: Microsoft Word 2007 (.docx), Open document format (.odt), markdown (.md). Default is docx and markdown.</p></body></html>"))
        self.butClose.setText(_translate("CompareDialog", "Close"))
        self.butCompare.setText(_translate("CompareDialog", "Compare"))
        self.comboABDifference.setItemText(0, _translate("CompareDialog", "A differ B (A - B)"))
        self.comboABDifference.setItemText(1, _translate("CompareDialog", "B differ A (B - A)"))
        self.comboABDifference.setItemText(2, _translate("CompareDialog", "A intersects B (A ∩ B )"))
        self.comboABDifference.setItemText(3, _translate("CompareDialog", "A union B (A ∪ B)"))

