# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(679, 640)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 653, 571))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.butClose1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butClose1.sizePolicy().hasHeightForWidth())
        self.butClose1.setSizePolicy(sizePolicy)
        self.butClose1.setObjectName("butClose1")
        self.gridLayout_4.addWidget(self.butClose1, 3, 4, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setMinimumSize(QtCore.QSize(561, 0))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.Settings = QtWidgets.QWidget()
        self.Settings.setObjectName("Settings")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.Settings)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.Settings)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 587, 183))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.comboDBselect = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboDBselect.sizePolicy().hasHeightForWidth())
        self.comboDBselect.setSizePolicy(sizePolicy)
        self.comboDBselect.setObjectName("comboDBselect")
        self.comboDBselect.addItem("")
        self.comboDBselect.addItem("")
        self.comboDBselect.addItem("")
        self.comboDBselect.addItem("")
        self.gridLayout_2.addWidget(self.comboDBselect, 1, 1, 1, 1)
        self.butUpdateDB = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.butUpdateDB.setObjectName("butUpdateDB")
        self.gridLayout_2.addWidget(self.butUpdateDB, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineOutputFilename = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineOutputFilename.setText("")
        self.lineOutputFilename.setObjectName("lineOutputFilename")
        self.gridLayout_2.addWidget(self.lineOutputFilename, 2, 1, 1, 1)
        self.butSelectOutput = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.butSelectOutput.setObjectName("butSelectOutput")
        self.gridLayout_2.addWidget(self.butSelectOutput, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.lineTempFile = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineTempFile.setObjectName("lineTempFile")
        self.gridLayout_2.addWidget(self.lineTempFile, 3, 1, 1, 1)
        self.butSelectTempFile = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.butSelectTempFile.setObjectName("butSelectTempFile")
        self.gridLayout_2.addWidget(self.butSelectTempFile, 3, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        self.lineSlist = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineSlist.setObjectName("lineSlist")
        self.gridLayout_2.addWidget(self.lineSlist, 4, 1, 1, 1)
        self.butSlist = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.butSlist.setObjectName("butSlist")
        self.gridLayout_2.addWidget(self.butSlist, 4, 2, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_7.addWidget(self.scrollArea_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.Settings, "")
        self.checklist = QtWidgets.QWidget()
        self.checklist.setObjectName("checklist")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.checklist)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.checklist)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setUsesScrollButtons(True)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tabSelect = QtWidgets.QWidget()
        self.tabSelect.setObjectName("tabSelect")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tabSelect)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_5 = QtWidgets.QLabel(self.tabSelect)
        self.label_5.setObjectName("label_5")
        self.gridLayout_9.addWidget(self.label_5, 0, 0, 1, 1)
        self.lineSpecies = QtWidgets.QLineEdit(self.tabSelect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lineSpecies.sizePolicy().hasHeightForWidth())
        self.lineSpecies.setSizePolicy(sizePolicy)
        self.lineSpecies.setBaseSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setItalic(False)
        self.lineSpecies.setFont(font)
        self.lineSpecies.setAutoFillBackground(False)
        self.lineSpecies.setObjectName("lineSpecies")
        self.gridLayout_9.addWidget(self.lineSpecies, 1, 0, 1, 1)
        self.butAddToTree = QtWidgets.QPushButton(self.tabSelect)
        self.butAddToTree.setObjectName("butAddToTree")
        self.gridLayout_9.addWidget(self.butAddToTree, 1, 1, 1, 1)
        self.tabWidget_2.addTab(self.tabSelect, "")
        self.tabMerge = QtWidgets.QWidget()
        self.tabMerge.setObjectName("tabMerge")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.tabMerge)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(20, 20, 461, 71))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineMergeChecklists = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineMergeChecklists.setObjectName("lineMergeChecklists")
        self.gridLayout_5.addWidget(self.lineMergeChecklists, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 1, 0, 1, 1)
        self.butMergeChecklists = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.butMergeChecklists.setObjectName("butMergeChecklists")
        self.gridLayout_5.addWidget(self.butMergeChecklists, 2, 1, 1, 1)
        self.butMerge = QtWidgets.QPushButton(self.tabMerge)
        self.butMerge.setGeometry(QtCore.QRect(480, 410, 99, 32))
        self.butMerge.setObjectName("butMerge")
        self.tabWidget_2.addTab(self.tabMerge, "")
        self.tabCompare = QtWidgets.QWidget()
        self.tabCompare.setObjectName("tabCompare")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.tabCompare)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 10, 513, 98))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 0, 2, 1, 1)
        self.butCompare = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.butCompare.setObjectName("butCompare")
        self.gridLayout_6.addWidget(self.butCompare, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.comboABDifference = QtWidgets.QComboBox(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboABDifference.sizePolicy().hasHeightForWidth())
        self.comboABDifference.setSizePolicy(sizePolicy)
        self.comboABDifference.setObjectName("comboABDifference")
        self.comboABDifference.addItem("")
        self.comboABDifference.addItem("")
        self.comboABDifference.addItem("")
        self.comboABDifference.addItem("")
        self.gridLayout_6.addWidget(self.comboABDifference, 2, 0, 1, 1)
        self.butCheckASelect = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.butCheckASelect.setObjectName("butCheckASelect")
        self.gridLayout_6.addWidget(self.butCheckASelect, 1, 1, 1, 1)
        self.lineChecklistB = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineChecklistB.setObjectName("lineChecklistB")
        self.gridLayout_6.addWidget(self.lineChecklistB, 1, 3, 1, 1)
        self.butCheckBSelect = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.butCheckBSelect.setObjectName("butCheckBSelect")
        self.gridLayout_6.addWidget(self.butCheckBSelect, 1, 4, 1, 1)
        self.lineChecklistA = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineChecklistA.setObjectName("lineChecklistA")
        self.gridLayout_6.addWidget(self.lineChecklistA, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.tabCompare, "")
        self.tabCombine = QtWidgets.QWidget()
        self.tabCombine.setObjectName("tabCombine")
        self.label_11 = QtWidgets.QLabel(self.tabCombine)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 338, 27))
        self.label_11.setObjectName("label_11")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tabCombine)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 40, 441, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineCombineChecklists = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineCombineChecklists.setObjectName("lineCombineChecklists")
        self.horizontalLayout.addWidget(self.lineCombineChecklists)
        self.butCombineChecklists = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.butCombineChecklists.setObjectName("butCombineChecklists")
        self.horizontalLayout.addWidget(self.butCombineChecklists)
        self.tabWidget_2.addTab(self.tabCombine, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 30, 441, 41))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineExcelFilePath = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineExcelFilePath.setText("")
        self.lineExcelFilePath.setObjectName("lineExcelFilePath")
        self.gridLayout_3.addWidget(self.lineExcelFilePath, 0, 0, 1, 1)
        self.butSelectExcel = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.butSelectExcel.setObjectName("butSelectExcel")
        self.gridLayout_3.addWidget(self.butSelectExcel, 0, 1, 1, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 70, 201, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.lineExcelColnum = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineExcelColnum.setObjectName("lineExcelColnum")
        self.horizontalLayout_2.addWidget(self.lineExcelColnum)
        self.butFormatName = QtWidgets.QPushButton(self.tab_3)
        self.butFormatName.setGeometry(QtCore.QRect(360, 80, 131, 32))
        self.butFormatName.setObjectName("butFormatName")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(0, 0, 201, 39))
        self.label_12.setObjectName("label_12")
        self.checkBox = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox.setGeometry(QtCore.QRect(210, 70, 121, 20))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.gridLayout_8.addWidget(self.tabWidget_2, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.checklist, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 5)
        self.butGenerateSp = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butGenerateSp.sizePolicy().hasHeightForWidth())
        self.butGenerateSp.setSizePolicy(sizePolicy)
        self.butGenerateSp.setObjectName("butGenerateSp")
        self.gridLayout_4.addWidget(self.butGenerateSp, 3, 3, 1, 1)
        self.butDeleteSelection = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butDeleteSelection.sizePolicy().hasHeightForWidth())
        self.butDeleteSelection.setSizePolicy(sizePolicy)
        self.butDeleteSelection.setObjectName("butDeleteSelection")
        self.gridLayout_4.addWidget(self.butDeleteSelection, 1, 0, 1, 1)
        self.butDeleteAll = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butDeleteAll.sizePolicy().hasHeightForWidth())
        self.butDeleteAll.setSizePolicy(sizePolicy)
        self.butDeleteAll.setObjectName("butDeleteAll")
        self.gridLayout_4.addWidget(self.butDeleteAll, 1, 1, 1, 1)
        self.treeWidget = QtWidgets.QTreeWidget(self.scrollAreaWidgetContents)
        self.treeWidget.setMouseTracking(False)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.treeWidget.setIndentation(10)
        self.treeWidget.setRootIsDecorated(False)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.header().setVisible(True)
        self.treeWidget.header().setDefaultSectionSize(60)
        self.treeWidget.header().setHighlightSections(True)
        self.treeWidget.header().setMinimumSectionSize(5)
        self.treeWidget.header().setSortIndicatorShown(True)
        self.gridLayout_4.addWidget(self.treeWidget, 2, 0, 1, 5)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 679, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.butClose1.setText(_translate("MainWindow", "Close"))
        self.label_3.setText(_translate("MainWindow", "DB"))
        self.comboDBselect.setItemText(0, _translate("MainWindow", "Vascular plants of Taiwan (APG IV)"))
        self.comboDBselect.setItemText(1, _translate("MainWindow", "Vascular plants of Taiwan (Flora of Taiwan 2nd Edi.)"))
        self.comboDBselect.setItemText(2, _translate("MainWindow", "Bird list of Taiwan (2014)"))
        self.comboDBselect.setItemText(3, _translate("MainWindow", "Plants of Japan (Ylist)"))
        self.butUpdateDB.setToolTip(_translate("MainWindow", "<html><head/><body><p>Update the checklist database</p></body></html>"))
        self.butUpdateDB.setText(_translate("MainWindow", "Update DB"))
        self.label_2.setText(_translate("MainWindow", "Export"))
        self.butSelectOutput.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select export checklist file. Supported file formats: Microsoft Word 2007 (.docx), Open document format (.odt), markdown (.md). Default is docx and markdown.</p></body></html>"))
        self.butSelectOutput.setText(_translate("MainWindow", "Select file ..."))
        self.label_6.setText(_translate("MainWindow", "Tempfile"))
        self.butSelectTempFile.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select temporary file to save common names, and this file can be loaded to generate checklist later</p></body></html>"))
        self.butSelectTempFile.setText(_translate("MainWindow", "Select file ..."))
        self.label_4.setText(_translate("MainWindow", "Batch"))
        self.butSlist.setText(_translate("MainWindow", "Select file ..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Settings), _translate("MainWindow", "Settings"))
        self.label_5.setText(_translate("MainWindow", "Common name / scientific name"))
        self.lineSpecies.setToolTip(_translate("MainWindow", "<html><head/><body><p>Input species name. Type part of common names/epithets/family to list similar names. </p><p>You can press enter or return to add it to the checklist.</p></body></html>"))
        self.butAddToTree.setText(_translate("MainWindow", "Add species"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabSelect), _translate("MainWindow", "Select species"))
        self.label_9.setText(_translate("MainWindow", "To be merged checklists"))
        self.butMergeChecklists.setText(_translate("MainWindow", "Select file ..."))
        self.butMerge.setText(_translate("MainWindow", "Merge"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabMerge), _translate("MainWindow", "Merge"))
        self.label_8.setText(_translate("MainWindow", "Checklist B"))
        self.butCompare.setText(_translate("MainWindow", "Compare"))
        self.label.setText(_translate("MainWindow", "Checklist A"))
        self.comboABDifference.setItemText(0, _translate("MainWindow", "A differ B (A - B)"))
        self.comboABDifference.setItemText(1, _translate("MainWindow", "B differ A (B - A)"))
        self.comboABDifference.setItemText(2, _translate("MainWindow", "A intersects B (A ∩ B )"))
        self.comboABDifference.setItemText(3, _translate("MainWindow", "A union B (A ∪ B)"))
        self.butCheckASelect.setText(_translate("MainWindow", "Select file ..."))
        self.butCheckBSelect.setText(_translate("MainWindow", "Select file ..."))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabCompare), _translate("MainWindow", "Compare"))
        self.label_11.setText(_translate("MainWindow", "To be combined checklists"))
        self.butCombineChecklists.setText(_translate("MainWindow", "Select file ..."))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabCombine), _translate("MainWindow", "Combine"))
        self.butSelectExcel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select export checklist file. Supported file formats: Microsoft Word 2007 (.docx), Open document format (.odt), markdown (.md). Default is docx and markdown.</p></body></html>"))
        self.butSelectExcel.setText(_translate("MainWindow", "Select file ..."))
        self.label_10.setText(_translate("MainWindow", "Column number"))
        self.lineExcelColnum.setText(_translate("MainWindow", "1"))
        self.butFormatName.setText(_translate("MainWindow", "Format"))
        self.label_12.setText(_translate("MainWindow", "Choose file to format names:"))
        self.checkBox.setText(_translate("MainWindow", "with header"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Format"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.checklist), _translate("MainWindow", "Checklists"))
        self.butGenerateSp.setText(_translate("MainWindow", "Export"))
        self.butDeleteSelection.setText(_translate("MainWindow", "Delete selected"))
        self.butDeleteAll.setText(_translate("MainWindow", "Delete all"))
        self.treeWidget.setSortingEnabled(True)
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Family"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "Name"))
        self.treeWidget.headerItem().setText(2, _translate("MainWindow", "Common name"))

