# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(651, 739)
        self.treeWidget = QtWidgets.QTreeWidget(Window)
        self.treeWidget.setGeometry(QtCore.QRect(20, 350, 601, 301))
        self.treeWidget.setMouseTracking(False)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.treeWidget.setIndentation(10)
        self.treeWidget.setRootIsDecorated(False)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.header().setVisible(True)
        self.treeWidget.header().setDefaultSectionSize(60)
        self.treeWidget.header().setHighlightSections(True)
        self.treeWidget.header().setMinimumSectionSize(5)
        self.treeWidget.header().setSortIndicatorShown(True)
        self.butDeleteSelection = QtWidgets.QPushButton(Window)
        self.butDeleteSelection.setGeometry(QtCore.QRect(20, 660, 127, 32))
        self.butDeleteSelection.setObjectName("butDeleteSelection")
        self.butDeleteAll = QtWidgets.QPushButton(Window)
        self.butDeleteAll.setGeometry(QtCore.QRect(150, 660, 131, 32))
        self.butDeleteAll.setObjectName("butDeleteAll")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Window)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 601, 137))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.butSelectTempFile = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.butSelectTempFile.setObjectName("butSelectTempFile")
        self.gridLayout_2.addWidget(self.butSelectTempFile, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboDBselect = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboDBselect.sizePolicy().hasHeightForWidth())
        self.comboDBselect.setSizePolicy(sizePolicy)
        self.comboDBselect.setObjectName("comboDBselect")
        self.comboDBselect.addItem("")
        self.comboDBselect.addItem("")
        self.comboDBselect.addItem("")
        self.gridLayout_2.addWidget(self.comboDBselect, 0, 1, 1, 1)
        self.lineOutputFilename = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineOutputFilename.setText("")
        self.lineOutputFilename.setObjectName("lineOutputFilename")
        self.gridLayout_2.addWidget(self.lineOutputFilename, 1, 1, 1, 1)
        self.butSelectOutput = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.butSelectOutput.setObjectName("butSelectOutput")
        self.gridLayout_2.addWidget(self.butSelectOutput, 1, 2, 1, 1)
        self.lineTempFile = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineTempFile.setObjectName("lineTempFile")
        self.gridLayout_2.addWidget(self.lineTempFile, 2, 1, 1, 1)
        self.butUpdateDB = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.butUpdateDB.setObjectName("butUpdateDB")
        self.gridLayout_2.addWidget(self.butUpdateDB, 0, 2, 1, 1)
        self.lineSlist = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineSlist.setObjectName("lineSlist")
        self.gridLayout_2.addWidget(self.lineSlist, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.butSlist = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.butSlist.setObjectName("butSlist")
        self.gridLayout_2.addWidget(self.butSlist, 3, 2, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Window)
        self.tabWidget.setGeometry(QtCore.QRect(20, 170, 601, 151))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.tabWidget.setFont(font)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tabSelect = QtWidgets.QWidget()
        self.tabSelect.setObjectName("tabSelect")
        self.lineSpecies = QtWidgets.QLineEdit(self.tabSelect)
        self.lineSpecies.setGeometry(QtCore.QRect(10, 40, 431, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lineSpecies.sizePolicy().hasHeightForWidth())
        self.lineSpecies.setSizePolicy(sizePolicy)
        self.lineSpecies.setBaseSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setItalic(False)
        self.lineSpecies.setFont(font)
        self.lineSpecies.setAutoFillBackground(False)
        self.lineSpecies.setObjectName("lineSpecies")
        self.label_5 = QtWidgets.QLabel(self.tabSelect)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 275, 20))
        self.label_5.setObjectName("label_5")
        self.butAddToTree = QtWidgets.QPushButton(self.tabSelect)
        self.butAddToTree.setGeometry(QtCore.QRect(460, 50, 121, 32))
        self.butAddToTree.setObjectName("butAddToTree")
        self.tabWidget.addTab(self.tabSelect, "")
        self.tabMerge = QtWidgets.QWidget()
        self.tabMerge.setObjectName("tabMerge")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.tabMerge)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(70, 10, 461, 71))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineMergeChecklists = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineMergeChecklists.setObjectName("lineMergeChecklists")
        self.gridLayout_5.addWidget(self.lineMergeChecklists, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 1, 0, 1, 1)
        self.butMergeChecklists = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.butMergeChecklists.setObjectName("butMergeChecklists")
        self.gridLayout_5.addWidget(self.butMergeChecklists, 2, 1, 1, 1)
        self.butMerge = QtWidgets.QPushButton(self.tabMerge)
        self.butMerge.setGeometry(QtCore.QRect(480, 410, 99, 32))
        self.butMerge.setObjectName("butMerge")
        self.tabWidget.addTab(self.tabMerge, "")
        self.tabCompare = QtWidgets.QWidget()
        self.tabCompare.setObjectName("tabCompare")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.tabCompare)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 10, 581, 113))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 0, 2, 1, 1)
        self.butCompare = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.butCompare.setObjectName("butCompare")
        self.gridLayout_6.addWidget(self.butCompare, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.comboABDifference = QtWidgets.QComboBox(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboABDifference.sizePolicy().hasHeightForWidth())
        self.comboABDifference.setSizePolicy(sizePolicy)
        self.comboABDifference.setObjectName("comboABDifference")
        self.comboABDifference.addItem("")
        self.comboABDifference.addItem("")
        self.comboABDifference.addItem("")
        self.comboABDifference.addItem("")
        self.gridLayout_6.addWidget(self.comboABDifference, 2, 0, 1, 1)
        self.butCheckASelect = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.butCheckASelect.setObjectName("butCheckASelect")
        self.gridLayout_6.addWidget(self.butCheckASelect, 1, 1, 1, 1)
        self.lineChecklistB = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineChecklistB.setObjectName("lineChecklistB")
        self.gridLayout_6.addWidget(self.lineChecklistB, 1, 3, 1, 1)
        self.butCheckBSelect = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.butCheckBSelect.setObjectName("butCheckBSelect")
        self.gridLayout_6.addWidget(self.butCheckBSelect, 1, 4, 1, 1)
        self.lineChecklistA = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineChecklistA.setObjectName("lineChecklistA")
        self.gridLayout_6.addWidget(self.lineChecklistA, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabCompare, "")
        self.tabCombine = QtWidgets.QWidget()
        self.tabCombine.setObjectName("tabCombine")
        self.label_11 = QtWidgets.QLabel(self.tabCombine)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 338, 27))
        self.label_11.setObjectName("label_11")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tabCombine)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 40, 561, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineCombineChecklists = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineCombineChecklists.setObjectName("lineCombineChecklists")
        self.horizontalLayout.addWidget(self.lineCombineChecklists)
        self.butCombineChecklists = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.butCombineChecklists.setObjectName("butCombineChecklists")
        self.horizontalLayout.addWidget(self.butCombineChecklists)
        self.tabWidget.addTab(self.tabCombine, "")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(Window)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(378, 670, 251, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.butGenerateSp = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.butGenerateSp.setObjectName("butGenerateSp")
        self.horizontalLayout_4.addWidget(self.butGenerateSp)
        self.butClose1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.butClose1.setObjectName("butClose1")
        self.horizontalLayout_4.addWidget(self.butClose1)
        self.label_7 = QtWidgets.QLabel(Window)
        self.label_7.setGeometry(QtCore.QRect(20, 330, 81, 16))
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Window)
        self.tabWidget.setCurrentIndex(0)
        self.butClose1.clicked.connect(Window.close)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "checklist generator"))
        self.treeWidget.setSortingEnabled(True)
        self.treeWidget.headerItem().setText(0, _translate("Window", "Family"))
        self.treeWidget.headerItem().setText(1, _translate("Window", "Name"))
        self.treeWidget.headerItem().setText(2, _translate("Window", "Common name"))
        self.butDeleteSelection.setText(_translate("Window", "Delete selected"))
        self.butDeleteAll.setText(_translate("Window", "Delete all species"))
        self.label_3.setText(_translate("Window", "Checklist DB"))
        self.butSelectTempFile.setToolTip(_translate("Window", "<html><head/><body><p>Select temporary file to save common names, and this file can be loaded to generate checklist later</p></body></html>"))
        self.butSelectTempFile.setText(_translate("Window", "Select file ..."))
        self.label_6.setText(_translate("Window", "Temporary file for local names"))
        self.label_2.setText(_translate("Window", "Export checklist file"))
        self.comboDBselect.setItemText(0, _translate("Window", "Vascular plants of Taiwan (APG III)"))
        self.comboDBselect.setItemText(1, _translate("Window", "Vascular plants of Taiwan (Flora of Taiwan 2nd Edition)"))
        self.comboDBselect.setItemText(2, _translate("Window", "Bird list of Taiwan (2014)"))
        self.butSelectOutput.setToolTip(_translate("Window", "<html><head/><body><p>Select export checklist file. Supported file formats: Microsoft Word 2007 (.docx), Open document format (.odt), markdown (.md). Default is docx and markdown.</p></body></html>"))
        self.butSelectOutput.setText(_translate("Window", "Select file ..."))
        self.butUpdateDB.setToolTip(_translate("Window", "<html><head/><body><p>Update the checklist database</p></body></html>"))
        self.butUpdateDB.setText(_translate("Window", "Update DB"))
        self.label_4.setText(_translate("Window", "Load local batch file"))
        self.butSlist.setText(_translate("Window", "Select file ..."))
        self.lineSpecies.setToolTip(_translate("Window", "<html><head/><body><p>Input species name. Type part of common names/epithets/family to list similar names. </p><p>You can press enter or return to add it to the checklist.</p></body></html>"))
        self.label_5.setText(_translate("Window", "Common name"))
        self.butAddToTree.setText(_translate("Window", "Add species"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSelect), _translate("Window", "Select species"))
        self.label_9.setText(_translate("Window", "To be merged checklists"))
        self.butMergeChecklists.setText(_translate("Window", "Select file ..."))
        self.butMerge.setText(_translate("Window", "Merge"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMerge), _translate("Window", "Merge"))
        self.label_8.setText(_translate("Window", "Checklist B"))
        self.butCompare.setText(_translate("Window", "Compare"))
        self.label.setText(_translate("Window", "Checklist A"))
        self.comboABDifference.setItemText(0, _translate("Window", "A differ B (A - B)"))
        self.comboABDifference.setItemText(1, _translate("Window", "B differ A (B - A)"))
        self.comboABDifference.setItemText(2, _translate("Window", "A intersects B (A ∩ B )"))
        self.comboABDifference.setItemText(3, _translate("Window", "A union B (A ∪ B)"))
        self.butCheckASelect.setText(_translate("Window", "Select file ..."))
        self.butCheckBSelect.setText(_translate("Window", "Select file ..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCompare), _translate("Window", "Compare"))
        self.label_11.setText(_translate("Window", "To be combined checklists"))
        self.butCombineChecklists.setText(_translate("Window", "Select file ..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCombine), _translate("Window", "Combine"))
        self.butGenerateSp.setText(_translate("Window", "Export"))
        self.butClose1.setText(_translate("Window", "Close"))
        self.label_7.setText(_translate("Window", "Checklist"))

